function Dec=FraDec3D(A,D,L)

% function Dec=FraDec(A,D,L)
% This function implement framelet decomposition.
% A ==== the data to be decomposed, which are in a square matrix.
% D ==== is the decomposition filter in 1D. In 2D, it is generated by tensor
% product. The filter D must be symmetric or anti-symmetric, which
% are indicated by 's' and 'a' respectively in the last cell of D.
% L ==== is the level of the decomposition.
% Dec ==== is the framlet coefficient which are in a cell.

% Written by Jian-Feng Cai.
% email: tslcaij@nus.edu.sg

nD=length(D);
SorAS=D{nD};
Dec=cell(nD-1,nD-1,nD-1);

for i=1:nD-1
    M1=D{i};
    tempi=ConvSymAsym3D(A,M1,SorAS(i),L);
    tempi=permute(tempi,[2 1 3]);
    for j=1:nD-1
        M2=D{j};        
        tempj=ConvSymAsym3D(tempi,M2,SorAS(j),L);
        tempj=permute(tempj,[3 2 1]);
        for k=1:nD-1
            M3=D{k};        
            tempk=ConvSymAsym3D(tempj,M3,SorAS(k),L);
            Dec{i,j,k}=permute(tempk,[2 3 1]);
        end
    end
end