function Rec=FraRec3D(C,R,L)

% function Rec=FraRec(C,R,L)
% This function implement framelet reconstruction.
% C ==== the data to be reconstructed, which are in cells in C{i,j} with
% C{1,1} being a cell.
% R ==== is the reconstruction filter in 1D. In 2D, it is generated by tensor
% product. The filter D must be symmetric or anti-symmetric, which
% are indicated by 's' and 'a' respectively in the last cell of R.
% L ==== is the level of the decomposition.
% Rec ==== is the reconstructed data.

% Written by Jian-Feng Cai.
% email: tslcaij@nus.edu.sg

nR=length(R);
SorAS=R{nR};

ImSize=size(C{1,1,1});
Rec=zeros(ImSize);

for i=1:nR-1
    temp=zeros(ImSize([2 1 3]));
    for j=1:nR-1
        temp2=zeros(ImSize([3 1 2]));
        for k=1:nR-1
            M3=R{k};
            temp2=temp2+ConvSymAsym3D(permute(C{i,j,k},[3 1 2]),M3,SorAS(k),L);
        end
        M2=R{j};
        temp=temp+ConvSymAsym3D(permute(temp2,[3 2 1]),M2,SorAS(j),L);
    end
    M1=R{i};
    Rec=Rec+ConvSymAsym3D(permute(temp,[2 1 3]),M1,SorAS(i),L);
end